refactor: add FS Router
vaadin/skeleton-starter-hilla-react pull request #187
Opened 2024-03-18 17:05 UTC by Lodin

Requires vaadin/hilla#2214 to be released

2024-03-18 17:31 UTC, platosha requested changes

2024-03-18 17:31 UTC, platosha commented on src/main/frontend/themes/skeleton-starter-hilla-react/styles.css
What's the intention for this file, is it just an example? If so, I'd suggest to remove it.

2024-03-18 17:31 UTC, platosha commented on src/main/frontend/views/$layout.tsx
> +  const currentTitle = useViewConfig()?.title ?? 'Hybrid example';
What about reading the default title from HTML?



```suggestion

const defaultTitle = document.title;

export default function MainLayout() {
  const currentTitle = useViewConfig()?.title ?? defaultTitle;
```

2024-03-19 10:20 UTC, Lodin commented on src/main/frontend/themes/skeleton-starter-hilla-react/styles.css
Well, actually, it existed as an empty file, so I just have added a some styles to make it prettier (without that style, the text field at the route page sticks to the main menu).

2024-03-20 13:47 UTC, platosha approved these changes

2024-03-20 13:48 UTC, platosha requested changes
Let's wait for Hilla 24.4.0.alpha16 before merging

2024-03-25 08:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/skeleton-starter-hilla-react?pullRequest=187) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/skeleton-starter-hilla-react?pullRequest=187) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: Artur-<br/>:white_check_mark: taefi<br/>:white_check_mark: tarekoraby<br/>:white_check_mark: cromoteca<br/>:white_check_mark: Lodin<br/>:x: platosha<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/skeleton-starter-hilla-react?pullRequest=187) it.</sub>

2024-03-25 08:43 UTC, platosha approved these changes

2024-03-25 09:18 UTC, merged